
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 33;
  public static final int LBRACKET = 47;
  public static final int LTEQ = 31;
  public static final int PERIOD = 44;
  public static final int DOUBLE = 5;
  public static final int LPAREN = 40;
  public static final int INTERFACE = 13;
  public static final int INT = 12;
  public static final int PRINTLN = 17;
  public static final int FOR = 9;
  public static final int MINUS = 26;
  public static final int STRINGCONST = 52;
  public static final int RPAREN = 41;
  public static final int SEMICOLON = 42;
  public static final int NOT = 39;
  public static final int AND = 36;
  public static final int LT = 30;
  public static final int INTCONST = 49;
  public static final int OR = 37;
  public static final int COMMA = 43;
  public static final int BOOL = 2;
  public static final int DOUBLECONST = 51;
  public static final int CLASS = 4;
  public static final int COMP = 34;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int IF = 10;
  public static final int THIS = 21;
  public static final int ID = 50;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int RBRACKET = 48;
  public static final int EQUAL = 38;
  public static final int TRUE = 22;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int NULL = 16;
  public static final int MOD = 29;
  public static final int BREAK = 3;
  public static final int VOID = 23;
  public static final int READLN = 18;
  public static final int LBRACE = 45;
  public static final int ELSE = 6;
  public static final int WHILE = 24;
  public static final int RBRACE = 46;
  public static final int BOOLCONST = 53;
  public static final int EXTENDS = 7;
  public static final int STRING = 20;
  public static final int FALSE = 8;
  public static final int DNE = 35;
  public static final int IMPLEMENTS = 11;
  public static final int GT = 32;
  public static final int NEWARR = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "BREAK",
  "CLASS",
  "DOUBLE",
  "ELSE",
  "EXTENDS",
  "FALSE",
  "FOR",
  "IF",
  "IMPLEMENTS",
  "INT",
  "INTERFACE",
  "NEW",
  "NEWARR",
  "NULL",
  "PRINTLN",
  "READLN",
  "RETURN",
  "STRING",
  "THIS",
  "TRUE",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "COMP",
  "DNE",
  "AND",
  "OR",
  "EQUAL",
  "NOT",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "PERIOD",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "INTCONST",
  "ID",
  "DOUBLECONST",
  "STRINGCONST",
  "BOOLCONST"
  };
}

